blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/adonisjs/core/discussions/new?category=japa
    about: If you can't get something to work the way you expect, ask a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/japa/runner/issues/new
    about: Suggest any ideas you have by creating a new issue
  - name: Documentation issue
    url: https://github.com/japa/japa.dev/issues/new
    about: For documentation issues, suggest changes on our documentation repository.